### ISSUE TITLE
The most useless thing that you have done in SASS?

### ISSUE THREAD

**Issue by studiorgb** [HugoGiraudel/ama#10]
I have seen a lot of totally useless but interesting things build on SASS. Im curious of your experiments.

**Comment by HugoGiraudel** [comment]
Chances are high that those silly useless experiments you've seen were from me. :D 

You can see all my Sass related work here: https://github.com/HugoGiraudel/awesome-sass. Among the most stupid things I've ever built, would be:

* [SassyBitwise](https://github.com/HugoGiraudel/SassyBitwise), an implementation of bitwise operators in Sass
* [SassyIteratorsGenerators](https://github.com/HugoGiraudel/SassyIteratorsGenerators), a partial implementation of ES6 generators and iterators in Sass
* [SassyJSON](https://github.com/HugoGiraudel/SassyJSON), a JSON parser fully implemented in Sass
* [SassySort](https://github.com/HugoGiraudel/SassySort), popular sorting algorithm implemented in Sass
