### ISSUE TITLE
Google ranking

### ISSUE THREAD

**Issue by mychriz** [HugoGiraudel/ama#104]
Hello, Hugo,
I have created a website that runs smoothly. It is linked to Google Analytics. However, when I search for this page, all subpages appear in the results list. It is enough for me if only the start page is listed. Do you have a suggestion how I should implement this? 

Thanks and greetings from Wuppertal
Chris

**Comment by HugoGiraudel** [comment]
Hello there!

I’m not a SEO specialist I must say, so I’m not sure I’ll be able to help too much… In my experience, having all your pages indexed is not a bad thing per se, as it will increase your overall relevance and ranking score. 

If you really don’t want some pages to be indexed, you could add a `noindex, nofollow` meta tag to them.

```html
<meta name="robots" value="noindex, nofollow" >
```

**Comment by mychriz** [comment]
So a file would make sense in which all subpages are excluded and therefore only the start page is displayed in Google.

And by the way, I think your work at N26 is great. You can hardly do banking better.
