### ISSUE TITLE
Tabs or Spaces

### ISSUE THREAD

**Issue by gccumber** [HugoGiraudel/ama#105]
@HugoGiraudel Hot button topic coming at ya! Tabs or spaces and why? I've been in debates with people, sometimes heated, over which is the proper way. Would love your slant.

**Comment by HugoGiraudel** [comment]
I prefer spaces, but I’m not precious as long as it’s consistent and enforced with Prettier. :)

**Comment by icylace** [comment]
I, too, prefer spaces but the best argument I've come across in favor of tabs is with regards to accessibility.

[This Reddit post](https://www.reddit.com/r/javascript/comments/c8drjo/nobody_talks_about_the_real_reason_to_use_tabs/) discusses how using tabs effectively addresses the accessibility concerns of two developers with different visual impairments working on the same team together. One developer uses a huge font size so they need to have a smaller indentation size to be able to work well while the other developer uses a much larger indentation size to be able to work well. The flexibility of tabs naturally accommodates this scenario.
