### ISSUE TITLE
About the 7-1 Pattern nowadays 

### ISSUE THREAD

**Issue by nuxion** [HugoGiraudel/ama#106]
Hi! I really liked your article about styling react components with a SASS approach  [styling-react-components-in-sass](https://hugogiraudel.com/2015/06/18/styling-react-components-in-sass/)

I wonder if today you would choose the same pattern, or instead what alternative would you recommend?

Thanks,
Best regards,
Xavier

**Comment by HugoGiraudel** [comment]
Hey!

I somehow completely missed that and am really sorry about it. I’ve been a little bit out of the Sass game for the last few years as we use Fela (CSS in JS) at N26. I would say, as far as Sass methodologies go, the 7-1 pattern is still pretty solid in my opinion. SMACSS, BEM and OOCSS also are strong (probably way more so) options.
