### ISSUE TITLE
Scaling architecture with theming

### ISSUE THREAD

**Issue by florianuphoff** [HugoGiraudel/ama#108]
Hey Hugo,

i stumbled over your profile and work a few times. Especially your work on Sass guidelines. I'm currenlty writing a masterthesis about (s)css code quality. 
So here my question(s):
Are you familiar with scaling (s)css architectures like smacss/oocss/atomic and itcss? Currently i am developing an architecture which scales and supports "building" themes. This means i have a base theme and you can apply certain "skins" to generate a theme for different clients.

If you are interested lets exchange our experiences and knowledge.
Thank you in advance,
Flo :)

**Comment by HugoGiraudel** [comment]
Hello Florian!

I am so sorry I missed this before… To be completely honest with you, I left CSS behind me for a few years now, so while I was quite in touch with CSS frameworks such as SMACSS, OOCSS, and ITCSS, I’m not too familiar with them anymore.

I know that theming was never really my strong suit though. It is mentioned in Sass Guidelines’ 7-1 architecture, but that’s quite anecdotal and I never really found a bulletproof way to handle them. That being said, I also never worked on a project doing proper theming which required a solid solution for it.

I’m sorry I’m not able to help more.
