### ISSUE TITLE
Is N26 IB CSR, SSR or both?

### ISSUE THREAD

**Issue by brgermano** [HugoGiraudel/ama#109]
Hello Hugo, how are you?

I'm making a research about internet bankings stack, and I started reading your article https://medium.com/insiden26/web-security-at-n26-d1b4644c32fb, and the doubt above arrised:

'Is N26 IB CSR, SSR or both?'

Thanks a lot for your time :-)

**Comment by HugoGiraudel** [comment]
Hello!

I’m sorry I missed that. Somehow I never read the notification. N26 is both server-side and client-side rendered, with an option to disable one or the other (never both ;)) at run time. :)
