### ISSUE TITLE
Studying abroad

### ISSUE THREAD

**Issue by netrules** [HugoGiraudel/ama#112]
**Hello, _Hugo_!**

I wanted to participate in the AMA, and ask, do you have any clue what you'd recommend to someone looking to study abroad? Here comes a few points which you can TL;DR:
<details> 
  <summary><b>I am a student</b> </summary>
I am studying Software Engineering in a local college ; a title holding similitude to B.Sc. in Computer Science. I became familiarized with scripting languages at a very young age, for which I advanced to OOP later on.
</details>
<details> 
  <summary><b>I love all cultures</b> </summary>
I am from a 3rd world country where economy is very weird, and I am privileged to live the life I do. Even though I'm not actually of superlative wealth, I am blessed with education and peers to teach me interesting subjects. I like forming relations, and have become more accepting of social diversity and have come to love different cultures.
</details>
<details> 
  <summary><b>What is interesting to me</b> </summary>
If it's any relevant, I have become interested in UX/UI due to some professors in college, and I found you because of a Stackbit theme using some functions you developed in scss. I am also interested in game development, even though I am mostly a back end developer, with interests regarding DevOps. 
</details>
<details> 
  <summary><b>What I pursue in education</b> </summary>
Somewhere I can receive financial help and a decent degree quality. I am looking to do a masters or secondary title regarding data, ops, dev or ux fields of study.
</details>
<details> 
  <summary><b>And Finally</b> </summary>
Thanks for taking the time to read all my mumbo jumbo. Don't even know if this will be read, or if it will be something to spark your interest, however, I accept any suggestions you might throw my way. I appreciate it. Mostly I want to get back into game development as an indie artist and actually build a portfolio based on it, but I also love UX -- applied to all sciences and fields, specially in computing and how it affects HCI and ergonomics. I also love back end development.
</details>

Aaaalso, I'd appreciate some job finding tips or outlook on life I could use on planning future paths to take. Thanks.

**Comment by HugoGiraudel** [comment]
Hello Santiago! Sorry for not replying earlier, I somehow missed your message. It seems you’re curious and passionate, which is a requisite to make it in this field — this and a good dose of privileges of course. 

I am not too sure what tip to give you. What helped me land a job when I started was building an online portfolio of some sort. I built small side projects, filled my GitHub profile with some code and wrote for my own blog every now and then. It wasn’t necessarily too much, but it was something to display, which is unfortunately important.

I used — and still use — Twitter to stay up to date with web development, although my usage of Twitter changed over the years. I followed less tech thought leaders talking about code, and more people talking about the tech industry as a whole and its problems. It helped me see our profession in a different perspective.

The only tip I would give you is to enjoy what you do, and don’t feel like you have to be crushing all the time. I’m not going to lie, it helps, and it’s nice to have recognition for open-spource and what not, but at the end of the day, this is not worth it if you‘re going to burn out in the first few years of your career. So find the balance between work and side-projects (or whatever it is) that works for you and that you can sustain on the long run.

I hope this helps. :)

**Comment by netrules** [comment]
Gotcha, thanks a lot! Serves me as an inspiration to keep building my portfolio and finally make it available online, what with all of the conditions we're living in at the moment. Giving it time to enjoy what I'm doing and also make sure I'm learning is definitely which I must remember, so thanks a lot for mentioning it. I agree with most of what you said, and definitely hope it may help along the way.

Regards.
