### ISSUE TITLE
Using calc to figure out bulletproof line-height

### ISSUE THREAD

**Issue by supersimplenet** [HugoGiraudel/ama#113]
Hi! I'm really impressed by your [Corner ribbon with trigonometry](https://hugogiraudel.com/2020/01/22/corner-ribbon-with-trigonometry/) post, since I tried to tackle the same issue, with no success, a few months ago.

I would like to know your opinion, on a much simpler formula I figure out to set optimal `line-height`, regardless of `font-size`: [Codepen](https://codepen.io/supersimplenet/pen/JjYGJLV)

**Comment by HugoGiraudel** [comment]
Hello! Thank you for the kind words. Your work on this line-height is pretty neat! Have you considered writing an article about it and how you figured it out?

**Comment by supersimplenet** [comment]
As a guest post on your blog? Sound goods to me :)

**Comment by HugoGiraudel** [comment]
Sounds nice. Feel free to get in touch at hugo.giraudel on Gmail. :)
