### ISSUE TITLE
What's the best book you've ever read?

### ISSUE THREAD

**Issue by sindresorhus** [HugoGiraudel/ama#13]

**Comment by HugoGiraudel** [comment]
Definitely [What If](http://www.amazon.com/What-International-Scientific-Hypothetical-Questions/dp/0544456866) from Randall Munroe (xkcd). 

![What if](http://skepchick.org/wp-content/uploads/2014/09/9780544272996_vert-06e2ae3280376562e953d8462d22dad9f82697d2-s99-c85.jpg)

**Comment by HugoGiraudel** [comment]
I’m going to add [Technically Wrong](https://www.amazon.com/Technically-Wrong-Sexist-Algorithms-Threats/dp/1681688611) from Sara Wachter-Boettcher as well.

![Technically Wrong book](https://msdevshow.com/2017/11/technically-wrong-with-sara-wachter-boettcher/book.jpg)
