### ISSUE TITLE
On a weekly basis, what is the percentage of your time that you spend working?

### ISSUE THREAD

**Issue by Zhouzi** [HugoGiraudel/ama#15]
Considering a week to be 100%, are you actually spending 90% working? 80%? 70%?...

**Comment by HugoGiraudel** [comment]
It depends. Is open-source contributing, mail replying, Twitter feeding and basically anything related to the tech industry considered as *working* in your question? :)

**Comment by Zhouzi** [comment]
Yep, by working I mean anything that's more or less related to the tech industry and your job.

**Comment by HugoGiraudel** [comment]
It should not be that hard to compute.
A typical day would probably be divided like so, very roughly: 

* between 7 and 8 hours sleep;
* between 8 and 9 hours working as my full-time job;
* between 1 and 3 hours working for me (article writing, book writing, side projects, open-source contributing...);
* everything else is “personal time” (usually divided between public transports, taking care of the flat and more importantly spending time with my girlfriend).

Which gives us an average 10 (8.5 + 1.5) hours a day for the tech industry. 10 on 24 is actually only 41% so I have to assume you excluded sleep time from the question. So it would be 10 on 16, at best, which gives us a 62.5%. 

It still seems a bit low to me, I spend probably more time than this working but it is getting hard to compute. For instance, I read books about web development in the public transports. Would you count this as working? It is not quite work, but at the same time it is directly related to what I do for a living. I could ask the same about reading articles about tech on my free time. Should it be work or personal time?

Anyway, this should give you a rough overview of how I deal with my work on a daily basis, which is I believe what you expected as an answer. :)

**Comment by Zhouzi** [comment]
Actually everything that's actually making you better at what you do could be considered as working (it all depends on how we define "working" but you get the point). Thanks for the answer, I like the pragmatic way of calculating all those stuff, I'll give it a try for myself!
