### ISSUE TITLE
Do you know how I miss you?

### ISSUE THREAD

**Issue by nicolas-scolari** [HugoGiraudel/ama#16]
Damn! ;)

**Comment by HugoGiraudel** [comment]
I know man. I miss you too! Let's Skype some time during the week-end / next week. :)

**Comment by nicolas-scolari** [comment]
Yup! With pleasure as usual ;p 
And a special kiss for Miss A'
See u Bro'

**Comment by HugoGiraudel** [comment]
Also I'll keep you updated for my trip back in France early August. Would be good if we could have lunch together or something. :)
