### ISSUE TITLE
What's your favorite TV show?

### ISSUE THREAD

**Issue by silvenon** [HugoGiraudel/ama#18]

**Comment by HugoGiraudel** [comment]
That's tough, I have seen so many good ones. I'll give you my favourites:

* Sherlock
* How I Met Your Mother
* The Big Bang Theory
* Game of Thrones
* Kaamelott (French)

Classic but goodies.

**Comment by silvenon** [comment]
Oh man, Sherlock is the best.

**Comment by silvenon** [comment]
American Vandal! ❤️❤️❤️
