### ISSUE TITLE
Recommendations for getting more involved in Open Source projects?

### ISSUE THREAD

**Issue by maxx1128** [HugoGiraudel/ama#23]
First off, big fan of your sitepoint articles. Your ones on Sass Maps and a Gulp Sass workflow have helped a ton.

Second, I'm a relatively new web developer and am hoping to get more involved in open source work like Github. Mainly with making my own versions of useful front-end tools, or anything else related to Sass or apps. But there's so much here I have no idea where to freaking start or even start looking. Any recommendations for an open-source newcomer to start getting more involved?

Lastly, what's your opinion of Thoughtbot's Refills components? Any circumstances you feel they're best used or avoided?

**Comment by HugoGiraudel** [comment]
Hello. Thanks for the kind words!

I am not entirely sure what I should tell you regarding open-source, so I'll just throw some ideas in there. Pardon me if it's a bit messy. On topic, I recommend you track issues about open-source on @sindresorhus' AMA repository: https://github.com/sindresorhus/ama/search?q=open-source&type=Issues&utf8=%E2%9C%93. You will probably learn a few things from a talented OSS contributor like him. ;)

For starters, I don't think you necessarily have to contribute to open-source projects. I mean, while it's a nice feeling I am not sure one should force it. It comes when it comes.

I think I started putting stuff on GitHub when I started actually building stuff. I found a way to do this or that, created a commented code snippet with a short documentation, and put all this in a repository. Even if you think your code won't be used by anybody remember that:

* you can't know that;
* it's a good practice to be its own contributor (review your own code, open issues for yourself...).

After a while, I started being more confident with Sass and decided to help other people with their code. I've been actively keeping track of interesting Sass repositories on GitHub (frameworks, grids, libraries...) and submitting pull-requests to fix even the tiniest things. There is no such thing as small contributions. It could be as simple as fixing a typo in a README, or improving a poorly written ternary condition.

Sooner or later, this whole GitHub and open-source thing will be a breeze for you and you will do it without even realising it. :)

**Comment by HugoGiraudel** [comment]
> Lastly, what's your opinion of Thoughtbot's Refills components? Any circumstances you feel they're best used or avoided?

This could benefit of being its own question. ;)
