### ISSUE TITLE
How does your overall process looks like when building a new side project?

### ISSUE THREAD

**Issue by Zhouzi** [HugoGiraudel/ama#24]
This question is pretty broad but it's just about having a big idea of your process, e.g:

What are the main phases? Do you start by writing down some stuff? Jumping right into the code? And then, do you actually share it? On what sites/medias?

**Comment by HugoGiraudel** [comment]
I usually don't have an idea out of nothing. Happened a while back when I was discovering Sass but it's not the case anymore. More often than not, I find a project idea while building something as part of my work or a side project already. Therefore, it often starts directly from the code.

So I try to extract what I want to be a standalone module or project, and then I iterate on it several times to polish it. I make sure to lint the code, test it extensively (although I don't usually write tests, booooo!) and write inline comments where needed. All in all I try to be proud of the code I have created.

Once I am at this point, I create a new GitHub repository, and put my code in there as an initial commit. Then, I take time to create a decent `README.md` file to explain what the project is about, how it works, what should be known, and so on.

If I have ideas of possible features / improvements, I open issues on the repository. I must say I like being my own contributor. When working on my own projects, I try to be as constructive and productive as on any other. I force myself to open meaningful issues and to review my own pull-requests.

When the project seems good enough to be shared, I tweet about it once or twice in the week. My twitter account is popular enough that I usually get some feedback quite quickly, helping me improve the code further.

If the project is really valuable, I write a short blog post about it to introduce it, explain how it works, how it can be used as well as give some example. Depending on the scope of the project, this kind of article is released either on my own blog, or on SitePoint.
