### ISSUE TITLE
Naming a breakpoint mixin in SASS

### ISSUE THREAD

**Issue by shadeed** [HugoGiraudel/ama#28]
Hello Hugo,

I'm working on a project where I have a single page containing a login form and other pages like dashboard, products listing..etc 
For the login page there is different breakpints:
- Tablet
- Desktop

The above breakpoints will be fully different in width from other pages, so the name of them shouldn't be something generic like (@include medium, @include desktop) since I'm using them only for the login page. 

So I did the following:

```sass
$login-box-tablet: 350px;
$login-box-desktop: 1100px;
```

```sass
@mixin login-tablet {
  @media (min-width: #{$login-box-tablet}){
    @content;
  }
}
```

```sass
@mixin login-desktop {
  @media (min-width: #{$login-box-desktop}){
    @content;
  }
}
```

Do you think that naming the mixins that way is good thing? If you think it could be better what would you suggest?

Thanks,

**Comment by HugoGiraudel** [comment]
Hello Ahmad. 

For starters, I do not like having a mixin per breakpoint. It is an unscalable solution, and completely defeats the purpose of using mixins. Remember, mixins can have parameters. We should use them when it makes sense.

Here is how I like to do things. Either I need an advanced breakpoint manager and I use [include-media](http://include-media.com/), or I go with something like described in Sass-Guidelines: http://sass-guidelin.es/#responsive-web-design-and-breakpoints.

I hope it helps. :)

**Comment by shadeed** [comment]
Make sense. I learned a new thing :) Thank you!

**Comment by Skoks** [comment]
Hello Hugo, 

I'm sorry, but it's still a little unclear how to properly name tweakpoints (unique breakpoint)? 

For example we have 3 site wide breakpoints: 

```
$breakpoints {
  'sm': 400px,
  'md': 800px,
  'lg': 1200px,
}

@include respond-to('md') {
  ...
} 
```

And we have 2 unique breakpoints, which we use for login page only. 
Let's say `600px` and `1000px` breakpoints.  

Will this be a right way to name these breakpoints ? 

```
$login-sm: 600px;
$login-lg: 1000px;

@include respond-to($login-lg) {
  ... 
}
```

I have also asked this question in your [Breakpoints and tweakpoints article](http://www.sitepoint.com/breakpoints-tweakpoints-sass/).

Thank you

**Comment by HugoGiraudel** [comment]
I'd say your example is good. I tend to avoid shortcut such as `sm`, `md` and `lg` and opt for full-length versions like `small`, `medium` and `large` as I feel like it makes more sense.

I like the *small* / *medium* / *large* (*tiny*, *huge*...) approach as it is device-agnostic, unlike *phone*, *tablet* and so on. On-topic, have you read: https://css-tricks.com/naming-media-queries/?
