### ISSUE TITLE
What would be a concrete exemple of 7-1 pattern in an Open Source project?

### ISSUE THREAD

**Issue by maxslayer44** [HugoGiraudel/ama#30]

**Comment by HugoGiraudel** [comment]
Hey.

I feel like Sass Guidelines is a decent example of stylesheets sticking to Sass Guidelines recommendations: https://github.com/HugoGiraudel/sass-guidelines/tree/gh-pages/_sass. Huhu.

If you really want to just get started, there is the boilerplate: https://github.com/HugoGiraudel/sass-boilerplate. It is not a live example of course, it's just about putting you on tracks.

This pattern being fairly recent and essentially good for not-too-large projects, I don't know a lot of projects using it right now, but I had a lot of feedback about people using it in their work life. :)
