### ISSUE TITLE
What do you think about Spain?

### ISSUE THREAD

**Issue by AdrianArroyoCalle** [HugoGiraudel/ama#35]
How do people from outside Spain thinks about Spain? and How do you think about Spain?

**Comment by HugoGiraudel** [comment]
Now that's an odd question. At least one that I didn't expect, for sure. :D

I have been to Spain once, when I was a kid, at 9 or so. I don't remember a good deal of it to be perfectly honest; it's not like I enjoyed the night life or anything. We were just in holidays with my parents, brother and sisters, so I remember the heat, the pool and the meals on the terrace.

I plan on going back at some point, hopefully, although my girlfriend is not really in the mood for latin countries, so it might take me a while before I can convince her to have a little “warm trip” in Spain. :)

Let me take this question as an opportunity to spread some clichés if you don't mind: when we French people think about Spain, we usually envision corridas and chorizo. Which are both pretty cool, you'll concede.

That's it. It seems like a lovely country, I just don't know much about it (pero hablo un poquito Español). :)
