### ISSUE TITLE
Do you speak German?

### ISSUE THREAD

**Issue by alfredbez** [HugoGiraudel/ama#36]

**Comment by HugoGiraudel** [comment]
I do not, although I plan to learn. A bit. :)

**Comment by HugoGiraudel** [comment]
It’s been 9 months. I learnt a few words. I still don’t speak German. :D

**Comment by alfredbez** [comment]
Hat sich in der Zwischenzeit etwas getan?

**Comment by HugoGiraudel** [comment]
Nein! 😇

**Comment by linusg** [comment]
Und wie sieht es jetzt aus? :wink:

**Comment by marcop135** [comment]
Did you learn it?

**Comment by KittyGiraudel** [comment]
I am ashamed to say I haven't progressed much. I can read it a bit and I can have small transactional exchanges (like ordering food, paying...). I can understand some conversations that I am not part of based on context. But no, I haven't actually learnt German. 🙃🫠

**Comment by marcop135** [comment]
Totally get that. German can be tough, especially when you’re surrounded by English. You're definitely not alone!

**Comment by KittyGiraudel** [comment]
I learnt some Dutch as well since my partner is Dutch and we have long term plans to move to the Netherlands. I also felt it was important to better understand them as a person. I prefer Dutch to German I must say, much easier and nicer to me.

**Comment by marcop135** [comment]
Oh, really? I lived and worked (in English) in Amsterdam for a while, so I have a basic grasp of the Dutch language. I agree that it's probably easier than German, but how do you feel it's nicer?

**Comment by KittyGiraudel** [comment]
I feel like the language structure and grammar is closer to English. Less cases and stuff. Pronunciation is challenging though for sure.

**Comment by marcop135** [comment]
I see. Thank you so much for sharing!
