### ISSUE TITLE
What's life like for nerds who make the move to Berlin?

### ISSUE THREAD

**Issue by Shipow** [HugoGiraudel/ama#39]

**Comment by HugoGiraudel** [comment]
Well, it's very good. Especially in the summer where Berlin is such an amazing city. There are always stuff to do, a lot of events to attend, and man, having lakes inside the city in so great when it's warm outside. Berlin is an amazing mix of so many different locations, neighbourhoods, ways of living, people, and much more.

Are you planning on making the move? :)

**Comment by Shipow** [comment]
I will visit the city for sure, but an upcoming event is about to change rules of the game :)
