### ISSUE TITLE
Future of Web Design, London 2016

### ISSUE THREAD

**Issue by Wispubs** [HugoGiraudel/ama#41]
Hi Hugo,

I'd like to introduce myself to you, I am a Conference Producer at Future Insights. I am getting in touch because we'd like to invite you to join us at Future of Web Design (FOWD) London 2016 which is taking place on 25-27 April.

Next year is special for us as FOWD London will be celebrating it's 10th anniversary! To mark this special occasion we will be celebrating the last ten years as well as looking to the future of web design and we'd be honoured to have you as a speaker.

We're looking for you to give a 40 minutes talk and in return, we’ll pay you a speaker fee, cover your travel and expenses, and generally make sure you are looked after.

I look forward to hearing from you and very much hope that you’ll be a part of FOWD London 2016!

Yours sincerely,
Veronica Cortes
veronica@futureinsights.com

**Comment by HugoGiraudel** [comment]
Well, that is an unexpected use of the AMA system I must say! :)

Thank you very much for getting in touch anyway, and be sure I will send you a mail in the few next days to talk about all this.

Best regards,
