### ISSUE TITLE
Equal padding around x-height of text?

### ISSUE THREAD

**Issue by Willadaygo** [HugoGiraudel/ama#42]
Hi Hugo, you're a SCSS God and I am not worthy, but I have a little question regarding web typography. I've tried to search for this but can't find a satisfactory solution. 

How does one get equal padding around some inline-block text, for example a button with exactly 20px around the whole of the text taking into consideration the x-height. I usually have to just use my eye and play around with the top and bottom padding or centring it with height and line-height. Is there some way of using the CSS ex unit some how? Also if you're using big letter-spacing, it can be troublesome getting the padding right.

Is there some mighty calculation that can solve this dilemma?

Many thanks

Will

**Comment by HugoGiraudel** [comment]
Hello!

I am not sure I know a bulletproof trick for this. For instance, left and right paddings might *look* different based on the opening and closing letters when using non-monospace fonts. I don't think there is anything you can do about this. Either the text is static in which case you can hack the padding to find a correct value, or it's dynamic and you gotta live with it.

Same goes for vertical paddings. Sometimes I found that setting `line-height` to `1` helps leveraging the difference between top and bottom paddings, especially with some fonts. It's not bulletproof though and again is more a hack than decent solution.

That being said I never really encountered a way where the visual difference between left and right or top and bottom was sensible enough that I felt the urge to fix it. I usually prefer staying away from magic numbers in my code when I can. 

I hope it helps!
