### ISSUE TITLE
Do you use a CSS naming convention?

### ISSUE THREAD

**Issue by tikitariki** [HugoGiraudel/ama#43]
Hey Hugo. Could you share your preferred CSS naming convention (or scoping style, if that is even a term) and why? Feel free to elaborate as much as possible. :)

**Comment by HugoGiraudel** [comment]
Hello,

I use [BEM](https://en.bem.info/), and I have been doing so for years now. It is an efficient CSS naming convention to keep things clean and tidy. By being meaningful with class names, we can avoid a lot of specificity issues. [Harry Roberts](http://csswizardry.com/) has been very convincing with this methodology, and I cannot recommend his articles enough: 
* http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/
* http://csswizardry.com/2015/08/bemit-taking-the-bem-naming-convention-a-step-further/
* http://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/

Regarding architecture, I use a system of my own called the [7-1 pattern](http://sass-guidelin.es/#the-7-1-pattern), which is (unintentionally similar to [SMACSS](https://smacss.com/) from [Jonathan Snook](http://snook.ca/)). It is heavily focused on Sass, but it has proven to work quite great on most projects. Many people told me good things about it, so I can only assume it's good. :)
