### ISSUE TITLE
Mixin for @font-face

### ISSUE THREAD

**Issue by mturnwall** [HugoGiraudel/ama#45]
I'm moving away from Compass to libsass for the speed improvements. I created my own @font-face mixin. I was thinking of putting it out into the wild for people to use. Any advice? Is it overkill or even needed? See any room for improvement?

Also it's documented using sassdocs, of course :smile: 
http://sassmeister.com/gist/fb89be11c454eb10e5ca

**Comment by HugoGiraudel** [comment]
Hey!

Thanks for getting in touch. I have been having a look at your code and here are a few comments on the top of my head:

* Use the `!default` flag for configuration variables
* Use hyphens only, not camelCase
* Do not redefine `$fonts-dir` inside `_fontFace` as this is not needed
* Do not enforce the usage of `eot` and `ttf`, maybe users want only `woff` and `woff2`
* Print the `@font-face` at root with `@at-root`
* Try to avoid having a same mixin with different signatures, it usually is not a good idea
* The `null` behaviour you imply is not obvious therefore doesn't look like a good idea to me
* I would advise against calling the mixin in a loop at root and wrap this up in a mixin so users can call it wherever they want
* It's good practice to namespace everything

For the record, here is how I would have built it: http://sassmeister.com/gist/ec1912cce6c48b381c32. :)

**Comment by mturnwall** [comment]
Thanks for the feedback!

* The thought behind putting `$fonts-dir` inside the mixin was to help encapsulate configuration into the mixin.
* I was thinking of allowing a user to specify the filetype but couldn't think of a way to do it. Since different file formats almost always have the same file name, how about just providing a list of formats to output rather than the extenstion:filename map?
* I really like the idea of at-root.
* Regarding the signature, is it bad in Sass to try to do overloading?

I always forget about the arglist in Sass. Thanks for pointing that out to me :smile: I'm going to make some updates and I'll post what I come up with.

**Comment by HugoGiraudel** [comment]
> The thought behind putting $fonts-dir inside the mixin was to help encapsulate configuration into the mixin.

You could also skip the variable altogether and use an argument I suppose.

> I was thinking of allowing a user to specify the filetype but couldn't think of a way to do it. Since different file formats almost always have the same file name, how about just providing a list of formats to output rather than the extenstion:filename map?

Because that is not always the case and it is as easy to provide a map mapping formats (not extension) to filenames.

> Regarding the signature, is it bad in Sass to try to do overloading?

It's better to keep things simple.

**Comment by mturnwall** [comment]
It's been a busy week, but I finally had some time to revisit this. I created a version that combines both versions of the mixins. The update outputs all the @font-face rules so that they have the same font name. This way it takes advantage of style linking.

I think this is a good hybrid of both versions.
http://sassmeister.com/gist/2f54cbe507422042fdaa

**Comment by HugoGiraudel** [comment]
I'm closing this then. :)
