### ISSUE TITLE
Do you participate in mentoring or coaching others?

### ISSUE THREAD

**Issue by jedireza** [HugoGiraudel/ama#48]

**Comment by HugoGiraudel** [comment]
Not yet. Well, I do speak at conferences, but I don't run classes or workshops if that is your question. That might change in the future though.

**Comment by tbrodard** [comment]
Did that change now ? Are you available for custom workshops ?

**Comment by HugoGiraudel** [comment]
Hey. I will likely be giving in a workshop as part of a 2-days event next year, but nothing is set in stone just yet so I can’t really tell more at this point. 

However I guess I am open to discussion about custom workshops and formations, of course. :)

**Comment by tbrodard** [comment]
Great !

Can I contact you in MP ? Send me your e-mail (no spam, promised ;-)

**Comment by HugoGiraudel** [comment]
Either @HugoGiraudel on Twitter, or hugo.giraudel on Gmail. :)
