### ISSUE TITLE
RFC. Sassiin framework.

### ISSUE THREAD

**Issue by tunnela** [HugoGiraudel/ama#49]
Hello Hugo,

Check out Sassiin framework https://github.com/tunnela/sassiin for Sass 3.4+! Powerful breakpoint system combined with declaration handlers, call-time generated variables and media query aware placeholders. Any thoughts from fellow Sass dev?

Thanks! ;)

**Comment by HugoGiraudel** [comment]
Hello there,

I had a look. It is an impressive piece of code, for sure. 

I’d say it would benefit from some code linting and extra documentation (SassDoc is there but no description whatsoever) but all in all it’s good! 

However I have a question that trumps everything else: why? It is massive, monolithic, and 95% of it will be completely useless on most projects. 

Sorry for being that straightforward, I just give you my raw opinion. I would never use anything that big, no matter how good it is. It is very nice for the fun of it and the challenge of making all these functions and mixins, but it has no real application use case. 

Hope my thoughts help. :)

**Comment by tunnela** [comment]
Thank you Hugo for using your time and being straightforward! It's always good to have someone else's opinion :)

Yup, you're right. There is no SassDoc descriptions yet. It's on my todo list. I admit, I'm kind of lazy writing comments in the code... :)

Did you notice the usage instructions [https://github.com/tunnela/sassiin#2-usage-instructions](https://github.com/tunnela/sassiin#2-usage-instructions)? I'm trying to explain there why some of the features were added (although incomplete).

Some ppl may find Sassiin quite massive which it really is. The code is also monolithic. However, if you are like me and pay attention to every detail on a website you might need Sassiin. Here is an example of how I've used Sassiin on one of my websites:

[https://gist.github.com/tunnela/cbab3451c8be84061f07](https://gist.github.com/tunnela/cbab3451c8be84061f07)

The stylesheet uses golden typography (http://www.pearsonified.com/2011/12/golden-ratio-typography.php) and without Sassiin it would've been quite impossible to change ie. the ratio between font size and line height. Every margin, padding and line height is based on the golden line height which changes per device width. Please see it in action at [http://drobbits.com/?password=preview](http://drobbits.com/?password=preview). So basically change in golden line height changes everything in the stylesheet.

Thanks Hugo!

**Comment by HugoGiraudel** [comment]
If there is one thing I have learnt in my job, it is that simple is always better than clever. :)
