### ISSUE TITLE
Do you translate any tutorials? Would you be interested in translating your content or others?

### ISSUE THREAD

**Issue by almakdad** [HugoGiraudel/ama#57]

**Comment by HugoGiraudel** [comment]
Hey there.

I don’t translate my work anymore. Before I went into web development, I was having a blog on World of Warcraft. I posted an article a day for almost a year on WoW news. To do so, I was doing a hell lot of translation from English to French. 

When I stopped WoW and started my career in the web industry, I told myself “translation no more”. For starters, it’s too time consuming. And not quite the fun. Also, our field is heavily English-based so having content in both French and English would not always be as useful as it could be.

The only exception to this has to be [Sass Guidelines](http://sass-guidelin.es) which exist in 12 languages so far, and 5 are about to be added in the next few months. This project being a very comprehensive document for everybody to learn more about Sass, it made sense to have it in as many languages as possible.

Now, I’m always happy to see my articles translated as long as they preserve a link to the original source. A few of my blog posts have been translated already. I find it great that some people take time to do that. :)

**Comment by almakdad** [comment]
Thanks for your response, Hugo!

Great idea for making Sass Guidelines multilingual!

I've been working on a project called [Native](http://getnative.me) with the objective to democratize access to easy-to-use translation tools and simplifying the crowdsourcing process for both content creators and translators. We're currently supporting both CSS Animation & EnvatoTuts+, among others, in their effort to translate their content (See examples for each below). I would love to get your feedback on the tool when you have some time, seeing how you have some experience translating and running a semi translation project ;-)

Mac 
Twitter: @malnakari

French translations are on the right hand side of the articles below:
**CSS Animation:** https://cssanimation.rocks/portal/
**Envato Tuts+:** http://webdesign.tutsplus.com/articles/ux-tip-consider-the-empty-states--cms-23692

**Comment by HugoGiraudel** [comment]
Hey there. I’m just coming back to this now, sorry for the delay. Do you think there is any way I could try this for Sass Guidelines maybe? Any chance I could put my hands on a trial version? :)

**Comment by almakdad** [comment]
Hi Hugo,

Absolutely! Are the source files for Sass Guiltiness in markdown by any chance? Could you share? I can try to set it up on Native and once you've created an account on Native, I will assign it to you so you can play around and try it. Native is open for anyone to signup: https://getnative.me/signup

**Comment by HugoGiraudel** [comment]
Oh, that’s great news! I can’t wait to try it. The translation system on Sass Guidelines always have been the bottleneck for contributions. You can read more about the issue in [this comment](https://github.com/HugoGiraudel/sass-guidelines/issues/96#issuecomment-191794516).

As of today, most of the content lives in Markdown files yes. For instance, the whole English version lives inside [this folder](https://github.com/HugoGiraudel/sass-guidelines/tree/gh-pages/en). Each chapter is its own file.

**Comment by almakdad** [comment]
Hi Hugo,

I have something to show you but it's on our dev server. It might be best if we could get on a quick Skype call to discuss in details? Please DM me on Twitter so we can exchange Skype IDs. Thanks!
