### ISSUE TITLE
Items on circle Article

### ISSUE THREAD

**Issue by Nic0205** [HugoGiraudel/ama#58]
Hi Hugo, 

i just saw your articles about sass and the items on circles. I just start with web development and in my case i just want to create a website for my smart home home automation. 

Therefore i want to you as radial menu but not as as a whole circle, but 270° degree (in german: Dreiviertelkreis) is it possible to modify your code so that the items are arranged at a 270° circle.

I would be pleased if you reply.

Greetings from Hamburg.

**Comment by HugoGiraudel** [comment]
Hey there. 

Instead of working on a 360° wheel for calculations, work on a 270 one. That should be quite straightforward I believe. It mostly comes down to this I think:

```scss
$angle: (270 / $nb-items);
```

**Comment by Nic0205** [comment]
Hey there. Thank you for replying.

In fact this solution works, But one thing would be nice to modify additional.

How Could i define on which Position  the free 90 degree piece is shown?

Could you have a second look for me?

**Comment by HugoGiraudel** [comment]
I’d go with:

```scss
$initial-position: 90deg;

transform: 
      // Rotate the axis
      rotate($initial-position + $rot * 1deg)
      // Move the item from the center
      translate($circle-size / 2)
      // Rotate the item back to its default position
      rotate($initial-position + $rot * -1deg);
```

**Comment by Nic0205** [comment]
That's it. Thank you!!!!!!

**Comment by HugoGiraudel** [comment]
Anytime. :)
