### ISSUE TITLE
What do you think of the french web scene?

### ISSUE THREAD

**Issue by Anahkiasen** [HugoGiraudel/ama#6]
French here, I see you do almost everything in english (as do I) although I saw the occasional article from you in french. What do you think of the french web scene, do you not participate in it much because you think it's lagging behind or is it simply, not enough time?

**Comment by HugoGiraudel** [comment]
I am not a big fan I must say. And this one of the reasons why I decided to go full English from the beginning of my career. It is slightly harder of course as English is not my native tongue, but there has not been a single day where I have regretted that choice so far.

The French tech industry is, I believe, an industry like the others in France. People are basically never happy, talk a lot (usually for bad reasons and without adding anything constructive to the discussion), and do very little. I generalise here of course, but this is my rough feeling about it.

We have very talented and popular developers in France, such as @kaelig, although most of them decide to go abroad after some years. It is a shame, but I feel like it conveys the idea that the French tech industry is not really the right place for those profiles, unfortunately. Talent is not always valued as it should be, salaries are quite poor compared to what can be achieved in some other countries, and the general tech industry is, I believe, still lagging behind some other more shiny places. 

Also I feel like a large part of the French tech industry is very close-minded. Take the quite hot topic that are preprocessors for instance. On a worldwide scale, there are people in favour, people against them, but mostly people don't give a fuck; they are just tool. Now when it comes to France specifically, I've seen a lot of people harassing each others because “LESS sucks”, because “Sass is bloated”, because “cssnext is the future”, because “Stylus is better at doing things”. Again: a lot of talking (and very unpleasant one you will concede), for basically no point.

Long story short, I think we could do much better. But French are French. ¯\_(ツ)_/¯

**Comment by lgiraudel** [comment]
Je suis pas vraiment d'accord et je trouve que tu généralises énormement.
Oui les français aiment raler et ce beaucoup plus que leurs voisins mais c'est pas spécifique à l'industrie tech (je doute que les développeurs français soit spécialement raleurs).

Les développeurs français sont aussi bons que ceux de n'importe quel pays (à dire vrai certaines études montrent que la France a des travailleurs très performants comparés à d'autres pays) par contre :
- on n'a pas vraiment de géants du web chez nous, du coup si on veut travailler pour les plus grosses entreprises il faut partir aux US (ou éventuellement dans leur antenne UK)
- l'american way of life attire plein de gens, et quand tu sais qu'avec ton profil tu auras un panel énorme de sociétés pouvant t'embaucher dans la Silicon Valley, ça aide à franchir le pas.

Les talents qui ne sont pas estimés à leur juste valeur, c'est pas faux. Un informaticien de plus de 40 ans qui n'est pas encore chef de projet est mal vu, en particulier en SSII. Par contre je ne sais pas si c'est spécifique à la France.
Ce qui nous impacte le plus, c'est la force du diplome. Un auto-didacte sans diplome aura beau être doué, il va plus galérer pour être reconnu au même niveau que son collègue ingénieur. Il aura plus de mal à dégotter ses premiers contrats, il aura plus de mal à avoir le même salaire et certaines entreprises lui fermeront la porte au nez parce qu'il lui manque un bout de carton.

Quand aux salaires, ils sont loin d'être dégueux. Faut pas regarder le brut en euros ou en dollars et comparer avec les autres pays. Evidemment un salaire américain ou anglais mets des étoiles dans les yeux quand tu vois que le brut annuel est sur 5 chiffres, mais une fois que tu as pris en compte le coût de la vie et les avantages du système français (sécurité sociale, retraites, etc), tu te rends compte que t'es aussi bien loti que n'importe qui.
Quand tu te rends compte qu'une fois diplomé ton premier salaire te places direct dans les 10 à 20% des citoyens les mieux payés de ton pays, tu sais que tu n'as pas à te plaindre.

Et les français sont pas spécialement étroits d'esprit. Les pro et anti pre-processors existent dans tous les pays, tu fais juste une fixette sur 1 ou 2 gus qui ont pondu un post-processor et le rabachent à tour de bras sur twitter.
L'humanité vit dans le conflit et l'industrie tech n'y échappe pas. Vi vs Emacs, Git vs SVN, Linux vs Windows, test before vs test after, pro-tests vs anti-tests, techno X vs techno Y, tout ça c'est des débats universels dans l'IT, ils n'ont rien de français.

Bref, sans être spécialement fier d'être français (ça m'est tombé dessus tout seul), je suis pas mécontent de travailler en France.

Maintenant, pour ce qui s'agit de la scene communautaire, la question est vite réglée : si on veut être un tant soit peu reconnu comme un expert dans son domaine afin de pouvoir interagir d'égal à égal avec d'autres références internationales du-dit domaine, il faut communiquer en anglais. Du coup, soit on passe 2 fois plus de temps pour le faire en 2 langues, soit on se limite à l'anglais pour être plus productif en terme de contenu publique.
Si on n'a pas de telles aspirations, rester sur du français ne pose pas spécialement de problème, faut juste accepter que le compteur de followers ou le nombre de pages vues sur son blog gardera des proportions raisonnables.
Personnellement je me fiche complètement d'avoir une popularité proche du néant, je préfère largement inonder les personnes avec qui je travaille au quotidien de conseils, de questions, de tutos ou d'articles, autrement dit faire évoluer mon environnement de travail et par la même occasion les gens que j'apprécie (qui me font évoluer aussi avec leurs propres conseils / questions / tutos / articles, c'est le principe de l'émulation) plutôt que de faire la même chose sur un blog pour de parfaits inconnus.

**Comment by HugoGiraudel** [comment]
> Je suis pas vraiment d'accord et je trouve que tu généralises énormement.

Oui, je l'ai dit. Je généralise beaucoup, mais ça donne un sentiment général. Je ne peux pas vraiment être spécifique sur une réponse de 20 lignes, et il n'en a pas forcément besoin non plus.

> Les développeurs français sont aussi bons que ceux de n'importe quel pays (à dire vrai certaines études montrent que la France a des travailleurs très performants comparés à d'autres pays) par contre :

J'en doute fortement. Dans les couches plus basses du software development, peut-être. On a de très bonnes écoles pour former des ingénieurs, et tu es bien placé pour le savoir, mais je suis loin d'être convaincu qu'on a une bonne tech front. 

> on n'a pas vraiment de géants du web chez nous, du coup si on veut travailler pour les plus grosses entreprises il faut partir aux US (ou éventuellement dans leur antenne UK) 

True, et c'est une des raisons pour laquelle la France connait une fuite des cerveaux dans notre industrie. On a malheureusement du mal à trouver de grands groupes stimulants, surtout quand on sort de la région parisienne. Ceci étant dit, je ne suis pas convaincu qu'il y ait besoin d'un grand groupe pour se faire plaisir dans nos métiers, mais c'est tout de suite plus intéressants de travailler à grande échelle.

> Ce qui nous impacte le plus, c'est la force du diplome. Un auto-didacte sans diplome aura beau être doué, il va plus galérer pour être reconnu au même niveau que son collègue ingénieur. Il aura plus de mal à dégotter ses premiers contrats, il aura plus de mal à avoir le même salaire et certaines entreprises lui fermeront la porte au nez parce qu'il lui manque un bout de carton.

C'est un peu le problème justement. Notre industrie est faite en grande partie d'auto-didactes. Malheureusement, les entreprises Françaises ne le réalisent pas et préféreront bien souvent embaucher un diplomé qui ne sera pourtant pas forcément plus compétent. Attention, je ne nie pas l'importance des diplômes ; je pense simplement qu'on accorde trop d'importance à ce facteur. Il y a d'autres choses qui jouent, mais trop souvent relayées au second plan.

> Quand tu te rends compte qu'une fois diplomé ton premier salaire te places direct dans les 10 à 20% des citoyens les mieux payés de ton pays, tu sais que tu n'as pas à te plaindre.

*Ton* premier salaire. C'est le cas quand tu sors d'une grande école comme l'Epita, l'Epitech, ou autre école top-notch qui t'assure d'avoir un boulot immédiatement, d'être cadre, et d'être bien payé dès le début de ta carrière. Mais encore une fois, l'industrie tech et surtout quand on en vient au front-end, n'est pas constituée (uniquement) d'ingénieurs et de diplômés de grandes écoles. Elle est faite de plein de profils différents : des diplômés, des non-diplômes, des étudiants, des reconvertis, et ainsi de suite. Malheureusement, tu ne peux pas prétendre à un poste de cadre / un bon salaire si tu n'as pas un bac +5 en France.

> Quand aux salaires, ils sont loin d'être dégueux. Faut pas regarder le brut en euros ou en dollars et comparer avec les autres pays. Evidemment un salaire américain ou anglais mets des étoiles dans les yeux quand tu vois que le brut annuel est sur 5 chiffres, mais une fois que tu as pris en compte le coût de la vie et les avantages du système français (sécurité sociale, retraites, etc), tu te rends compte que t'es aussi bien loti que n'importe qui.

Ça rejoint mon point précédent. Les salaires sont bons si tu es ingénieur. Par exemple, je sais que je n'aurai jamais ton salaire en France. Même dans 8 ans. Ça n'arrivera pas. J'ai un bac +2 et un niveau licence que j'ai tout simplement foiré. Il n'y a pas une entreprise qui me payera comme un ingé, peu importe mon niveau et mon expérience.

> Et les français sont pas spécialement étroits d'esprit. Les pro et anti pre-processors existent dans tous les pays, tu fais juste une fixette sur 1 ou 2 gus qui ont pondu un post-processor et le rabachent à tour de bras sur twitter.
> L'humanité vit dans le conflit et l'industrie tech n'y échappe pas. Vi vs Emacs, Git vs SVN, Linux vs Windows, test before vs test after, pro-tests vs anti-tests, techno X vs techno Y, tout ça c'est des débats universels dans l'IT, ils n'ont rien de français.

Haha. On est une nation d'étroits d'esprit. Et ça n'a rien à voir avec notre industrie. On a des problèmes de racisme, d'homophobie, de transphobie, d'islamophobie, et j'en passe. Il y a peu de pays en Europe qui ont autant de soucis avec la différence que la France. 

Alors effectivement, je ne vais pas comparer la désappréciation des pré-processeurs avec l'homophobie ou l'islamophobie, ce serait déplacé, mais toujours est-il que l'étroitesse d'esprit Française, on la ressent aussi dans notre industrie. La critique est toujours là, au bout du commit, et c'est pénible. On peut essayer de passer outre, mais c'est simplement ignorer le problème. 

Plusieurs membres de la communauté front Française m'ont quand même dit que je devais faire attention à ce que je push sur GitHub sous prétexte que j'ai un compte Twitter actif. Quand tu entends ce genre de saloperies, tu te rends compte qu'on a quand même des soucis. Même sujet, le seul article Français que j'ai écrit (car on m'a invité à le faire) m'a attiré un certain nombre de trolls. C'est simplement constant : tu ne peux pas publier quelque chose en Français sans avoir des critiques néfastes / non-constructives. C'est usant, et c'est quelque chose que je n'ai personnellement pas ressenti dans l'industre anglophone.

> Maintenant, pour ce qui s'agit de la scene communautaire, la question est vite réglée : si on veut être un tant soit peu reconnu comme un expert dans son domaine afin de pouvoir interagir d'égal à égal avec d'autres références internationales du-dit domaine, il faut communiquer en anglais. Du coup, soit on passe 2 fois plus de temps pour le faire en 2 langues, soit on se limite à l'anglais pour être plus productif en terme de contenu publique.

Point made. 

> Si on n'a pas de telles aspirations, rester sur du français ne pose pas spécialement de problème, faut juste accepter que le compteur de followers ou le nombre de pages vues sur son blog gardera des proportions raisonnables.
> Personnellement je me fiche complètement d'avoir une popularité proche du néant, je préfère largement inonder les personnes avec qui je travaille au quotidien de conseils, de questions, de tutos ou d'articles, autrement dit faire évoluer mon environnement de travail et par la même occasion les gens que j'apprécie (qui me font évoluer aussi avec leurs propres conseils / questions / tutos / articles, c'est le principe de l'émulation) plutôt que de faire la même chose sur un blog pour de parfaits inconnus.

Chacun son truc. On a la chance de vivre dans une industrie formidable, largement basée sur le partage des connaissances et l'entraide. Je n'en serais pas là aujourd'hui si tant de gens compétents n'avaient pas partagé leur expérience et leur savoir sur internet. Je n'en serais pas là non plus si je n'en avais pas fait de même.

**Comment by ffoodd** [comment]
Je ne veux pas nourrir le troll, mais quand @HugoGiraudel a commencé à m’aider sur a11y.css il m’a convaincu de l’intérêt de le faire en anglais.

Je dis bien convaincu, car la question que je me suis posée peut être formulée ainsi : faisant ce même constat que la scène française est soit méconnue soit simplement moins « à la pointe », est-ce que travailler en Français et publier des outils en Français ne ferait pas avancer plus facilement ladite communauté ?

C’est pour cette raison que je continue à maintenir une version française, mais force est aussi de constater que fort peu d’outils prennent en considération le multilinguisme (par exemple, sans avoir trop cherché, il me semble que SassDoc ne va pas m’aider sur le sujet - je serais heureux de me tromper la-dessus). Sans être un puriste, j’aurais toujours tendance à favoriser le Français malgré le frein que ça pourrait constituer pour obtenir la reconnaissance de mes pairs.

Question salaire et entreprise, j’aimerais ajouter une dimension non évoquée : le changement dans le temps.

Question salaire à l’embauche, ça m’ennuie mais Hugo a raison. Personnellement, avec bac +3 en poche, j’ai démarré en tant qu’intégrateur au SMIC. Loin d’être dans les 10 / 20% de français les mieux payés. En revanche je rejoins Loïc sur le fait qu’on peut se développer et avancer rapidement dans certaines entreprises françaises. Ça me prendra certes un certain temps pour rattraper un développeur qui sort d’une école d’ingénieurs, mais je sais que je vais y parvenir.

Pour la question du mauvais esprit français, il faut aussi prendre en compte les gens qui s’expriment pas ou peu, ou différemment. Personnellement  lors de chaque événements comme Paris Web, je ne rencontre que des gens géniaux et extrêmement intéressants, mais qui ne publient presque rien et ne participent que trop peu à la communauté. Cela me frustre beaucoup car lorsque je fais des recherches je passe systématiquement par la case ressources en anglais, alors certains professionnels français ont un niveau d’expertise extrême sur le sujet mais ne le partage pas. Pour cette raison (et d’autres) j’admire les personnes comme Hugo, Kaelig, Rudy Rigot et j’en passe.

Désolé si je remets de l’huile sur le feu, bien que je me sente à cheval entre vos deux positions. C’est un sujet passionnant et je pense que Hugo a une vision très particulière, mais aussi et surtout une philosophie réaliste.

**Comment by Anahkiasen** [comment]
Pour moi ce qui m'a le plus embêté c'est la réticence des boîtes à faire de l'emploi à distance, alors que dès que j'ai cherché dans d'autres pays j'ai tout de suite trouvé. Toutes les offres en France fallait que je bouge sur Lyon, Paris etc alors que dans ma boîte actuelle on est tous à distance répartis à travers le globe et tout se passe absolument parfaitement. Mais non, il y a cette idée reçue qu'il faut que l'employé soit _dans les bureaux_ à faire du 8 à 8 là où il peut être surveillé et contrôlé, alors que moi ça me fais chier, trop de distractions et de trucs et de machins dans un bureau. Là je suis chez moi, je fais mes horaires avec ma boîte, et je travaille bien mieux que si j'avais tous les temps des collègues à me demander des trucs.

J'avais beaucoup galéré à l'époque parce que moi ma spécialisation c'est Laravel qui était quand même bien populaire aux US à l'époque et pas une seule offre en France, le framework était complètement méconnu. Et j'ai l'impression que y a un train de retard assez conséquent quand je regarde les offres d'emploi de temps en temps pour rigoler, des trucs qui sont déjà en passe d'être remplacés style AngularJS sont à peine arrivés en France il y a quelques années.

**Comment by ffoodd** [comment]
Tout dépend ou tu regardes :/

Dans ma boîte, entre 10 et 15% des employés travaillent à distance. Le point sur le train de retard est assez vrai, mais ça me semble être une conséquence directe du fait que les plus brillants s’en aillent et ne partagent que très peu au niveau français. 

De plus, je le perçois encore autour de moi, beaucoup de choses sont en train d’évoluer en France. Peut-être plus lentement qu’ailleurs, je le concède volontiers.

**Comment by morkro** [comment]
I really would like to follow this discussion. Anyone can sum it up, if possible?

**Comment by HugoGiraudel** [comment]
I'll give you a heads up next time we meet for a beer. ;)

**Comment by morkro** [comment]
Sounds great, reminds me to ask you! Follow up on Twitter :D

This is by the way in general an interesting topic to talk about. We have the same in Germany with _different problems_. The biggest reason for me is simply that web development and the internet is an international thing. It just doesn't makes sense to me to limit myself to a specific language/region. If I really want to contribute to the web scene, I have to reach the most people possible.

**Comment by ffoodd** [comment]
Please forgive me :/ I'm sure Hugo will sum this up :)

Your point is very good, but the same argument could be used to think that we don't even care where a web tech come from. If so, why would we be interested by a specific country web scene, or even thinking about comparison?

I'm not sure where my ideas are going to!

As a note, the french law about work are very hard, fat and unusually complex. That may explain a lot of things, too…

**Comment by lgiraudel** [comment]
> J'en doute fortement. Dans les couches plus basses du software development, peut-être. On a de très bonnes écoles pour former des ingénieurs, et tu es bien placé pour le savoir, mais je suis loin d'être convaincu qu'on a une bonne scène front. Je veux bien voir les études qui montrent le contraire cela dit.

Je ne parle pas de scène parce qu'effectivement la scène front française est minimaliste, je parle plutôt de compétences. On a des développeurs très compétents, que ce soit en front ou en back. Je suis incapable de dire si on est meilleur ou non que d'autres pays (qui le peut ?) mais on n'a pas à rougir pour autant.
Après, quand on regarde twitter, on se rend juste compte que la plupart des techos qu'on suit sont américains (ou plutôt bossent aux US). Sont-ils meilleurs que les autres pour autant ? J'ai tendance à penser qu'ils ont juste plus l'opportunité de travailler dans des sociétés à forts challenge, ce qui les place de facto comme des experts sur certaines compétences.

Pour les études, je n'ai rien trouvé propre à l'IT, par contre de nombreuses études placent les français comme les plus productifs par rapport au temps consacré au travail. Les résultats varient en fonction des études (et probablement en fonction de leur date), mais globalement la France se situe souvent dans le top 5.
Quelques articles sur le sujet:
http://www.diplomatie.gouv.fr/fr/politique-etrangere-de-la-france/diplomatie-economique-et-commerce-exterieur/actualites-liees-a-la-diplomatie-economique-et-au-commerce-exterieur/2014-23094/article/les-francais-au-quatrieme-rang
https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(PPP)_per_hour_worked
http://blog.pgi.com/wp-content/uploads/2014/07/Winding-down-the-work-week_PGi.png

> C'est un peu le problème justement. Notre industrie est faite en grande partie d'auto-didactes. Malheureusement, les entreprises Françaises ne le réalisent pas et préféreront bien souvent embaucher un diplômé qui ne sera pas forcément plus compétent pour autant. Attention, je ne nie pas l'importance des diplômes ; je pense simplement qu'on accorde trop d'importance à ce facteur. Il y a d'autres choses qui jouent, mais sont trop souvent relayées au second plan. Si bien que tu peux te faire griller une place par un diplomé sans même accéder à un entretien simplement parce qu'il est indiqué +2 sur ton CV et +5 sur le sien.

Le diplômé ne sera pas forcément plus compétent que l'auto-didacte, mais le fait qu'il soit diplômé va directement situer son niveau aux yeux du recruteur.

Ce qui compte c'est l'expérience, et sur un CV assez vierge, le diplôme c'est déjà un peu d'expérience. 
Après je ne nie pas que certains recruteurs ne cherchent même pas à aller plus loin quand ils ne voient pas un certain niveau d'étude mais plus le candidat a de l'expérience et moins le diplôme a de l'importance (sauf pour certaines grosses sociétés qui ont des grilles de salaires qui font qu'elles ne peuvent embaucher que des ingé, même quand le candidat a 15 ans de dev dans les pattes).

> Ça rejoint mon point précédent. Les salaires sont bons si tu es ingénieur. Par exemple, je sais que je n'aurai jamais ton salaire en France. Même dans 8 ans. Ça n'arrivera pas. J'ai un bac +2 et un niveau licence que j'ai tout simplement foiré. Il n'y a pas une entreprise qui me payera comme un ingé, peu importe mon niveau et mon expérience.

Non, là tu te trompes, je bosse avec certains développeurs qui ne sont pas ingé et qui ont le même salaire que moi. A partir d'une certaine expérience, c'est elle qui impacte le salaire d'entrée dans une boîte et ensuite ce sont les performances au sein de la boîte. L'absence de diplôme c'est un artguemnt qui sert surtout pour les SSII pour se faire une plus grosse marge sur les presta.

> Plusieurs membres de la communauté front Française m'ont quand même dit que je devais faire attention à ce que je push sur GitHub sous prétexte que j'ai un compte Twitter actif. Quand tu entends ce genre de saloperies, tu te rends compte qu'on a quand même des soucis. Même sujet, le seul article Français que j'ai écrit (car on m'a invité à le faire) m'a attiré un certain nombre de trolls. C'est simplement constant : tu ne peux pas publier quelque chose en Français sans avoir des critiques néfastes / non-constructives. C'est usant, et c'est quelque chose que je n'ai personnellement pas ressenti dans l'industre anglophone.

Je pige pas, faudra que tu m'expliques. Et si tu veux j'irai leur dire de pas être méchant avec mon ptit frère :)

@Anahkiasen : effectivement, la frilosité concernant le télé-travail (que ce soit à temps plein ou à temps partiel) est encore beaucoup trop importante.
Ca me fait penser à ma précédente boîte où ils avaient commencé à autoriser le télétravail mais uniquement les jours du milieu de la semaine, le lundi et le vendredi n'était pas autorisé. Dans le genre confiance dans l'employé, on fait mieux.

Dans notre métier ça a tendance à s'améliorer quand même, et encore plus dans le milieu du web. Déjà parce que d'un point de vue infrastructure technique, on se déplace de plus en plus vers du cloud.

@morkro : sorry to have made this topic switched to french :(
but you made the point : web is international and our job are moving pretty fast from a framework / tool / process to another which force us to keep on english to stay up-to-date.

@ffoodd yeah, french law put the employee before the employer. It's really hard to fire an employee and so HR take really care to hire the perfect person. I think it's a good thing for some professions, especially for laborer, but for other professions like IT where it's not so hard to find another job, maybe it's more an obstacle for both companies and employees.
