### ISSUE TITLE
Percentages in a circle

### ISSUE THREAD

**Issue by Primajin** [HugoGiraudel/ama#60]
Hi Hugo,

I stumbled across Ana's Rainbowwheel here: https://codepen.io/thebabydino/pen/hkxGp
In the comments on the right, in explanation of the code, she links to your page, which is currently 404: http://hugogiraudel.com/blog/css-gradients

I wanted to rewrite Ana's code into a scss mixin but I cant get my head around the numbers `24.52%, 42.34%, 57.66% and 75.48%`.

Where do they come from? What is the correlation between 10 Steps in a 360deg Circle and these exact numbers? How would I dynamically calculate those inside my mixing?

I would like to be able by determing the length of a colors list to dynamically generate these umbrella wheels.
Furthermore, since these are gradients, I would like to have the possibility to have the colors overlapping / mixing.

Would be great if you could help

All the best
Jannis

**Comment by HugoGiraudel** [comment]
Hey. The article would be here: http://hugogiraudel.com/2013/02/04/css-gradients/. :)

How about you give it a read and if you still can't figure it out, I check if I can give you a hand? :)

**Comment by Primajin** [comment]
Great, thanks for the link! I'll go on reading then ;)

**Comment by HugoGiraudel** [comment]
Cheers. :)

**Comment by Primajin** [comment]
OK so I went through and tried to adapt my calculations / mixins, now I feel like my brain is fried.
First I get different values for the calculations. Since there are no sin and cos functions in plain sass/scss (without compass) I got some from here: https://unindented.org/articles/trigonometry-in-sass/
First I thought the functions are wrong, but then I ran the calculation via http://www.wolframalpha.com/input/?i=sin(36deg)+%2F+(sqrt(2)+*+cos(9deg)) which says: 
`sin36°/(sqrt(2)*cos9°) = 0.4208` not `0.4234`

So I'm still not really able to extrapolate from there about the corresponding BOE to have 9° at 36° but how does it react with other angles, like the 72° and those that are negative and on the other semicircle.

As stated earlier I would like to create a mixin but I think Ana already used one - Is it also in the article / codepens? I couldn't find it. On top it would be even better to have a version where the colors mix into each other, so I wouldn't have to apply the blur filter on top that creates problems in Safari Browsers / iOS.

Without blur:
![without-blur](https://cloud.githubusercontent.com/assets/1742115/14787182/9e4f3916-0b02-11e6-9975-0749149f8a65.png)

With blur:
![with-blur](https://cloud.githubusercontent.com/assets/1742115/14787183/9e4f72d2-0b02-11e6-8bae-78b63243e8e2.png)
Ideally I would like to get this out of the box, with the possibility to add / remove color steps.

**Comment by HugoGiraudel** [comment]
Hey.

I have been going through the article and Ana’s demo but I am afraid that is a bit over my head unfortunately. I guess your best bet here would be to ask Ana directly to have a look at this, because I cannot help you with this. I am very sorry. :(

**Comment by Primajin** [comment]
Allright, thanks nevertheless!
