### ISSUE TITLE
Hello Hugo ! 

### ISSUE THREAD

**Issue by alexandredana** [HugoGiraudel/ama#61]
Je n'avais jamais vu cette utilisation de GitHub, cela me plaît bien , moi qui utilise GH pour tout même la comptabilité.. 

Je voulais te proposer d'être formateur pour un nouveau format de cours que nous lançons cet été avec LiveMentor

Je serais ravi de faire un Skype avec toi pour te présenter cet ambitieux projet,

Alexandre

**Comment by HugoGiraudel** [comment]
Hey Alexandre,

J’aimerais bien mais là ça va être très difficile pour moi de débloquer un moment d’ici 10 jours. J’ai un emploi du temps bien chargé ces temps-ci.

N’hésite pas à m’ajouter sur Skype néanmoins (hugo.giraudel).

**Comment by alexandredana** [comment]
ok je t'ajoute!



Alexandre Dana
+33 (6) 80 55 14 18
www.livementor.com
Twitter : @alexandredana <http://www.twitter.com/alexandredana>

2016-04-30 14:12 GMT+02:00 Hugo Giraudel <notifications@github.com>:
