### ISSUE TITLE
SASS Flexbox mixins

### ISSUE THREAD

**Issue by mmjaeger** [HugoGiraudel/ama#62]
Hello Hugo
browsed thru your repositories and was hoping to find some flex box grid mixins - can you recommend some decent grid mixins using flex box?

Thanks

**Comment by HugoGiraudel** [comment]
Hello there,

What do you mean by flexbox mixins? What do you except? Is this about vendor prefixes? Syntactic sugar? What for?

**Comment by mmjaeger** [comment]
Thank you for replying Hugo and sorry for not being more specific - I'm
looking for some decent scss mixins to create rows and columns (grids),
preferably one that allows for either padding or margin as gutter.

On Sun, May 22, 2016 at 2:00 AM, Hugo Giraudel <notifications@github.com>
wrote:

> Hello there,
>
> What do you mean by flexbox mixins? What do you except? Is this about
> vendor prefixes? Syntactic sugar? What for?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/HugoGiraudel/ama/issues/62#issuecomment-220821595>
>



-- 
Marco M. Jaeger
http://net4visions.com

**Comment by HugoGiraudel** [comment]
I did not work so much with Sass + flexbox. I mean, not in a generic way that would interest you. Have you had a look at http://flexboxgrid.com/?

**Comment by maxx1128** [comment]
Sorry to shamelessly self-plug here, but if it's about Sass mixins for Flexbox grids, I made something along those line a short while back called Ellisha. See it here: http://maxwellantonucci.com/Ellisha/

**Comment by mmjaeger** [comment]
I did, but it's kind of overkill for what I need and it's all plain css, no
SASS

On Sun, May 22, 2016 at 1:08 PM, Max Antonucci <notifications@github.com>
wrote:

> Sorry to shamelessly self-plug here, but if it's about Sass mixins for
> Flexbox grids, I made something along those line a short while back called
> Ellisha. See it here: http://maxwellantonucci.com/Ellisha/
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/HugoGiraudel/ama/issues/62#issuecomment-220853239>
>



-- 
Marco M. Jaeger
http://net4visions.com

**Comment by HugoGiraudel** [comment]
Why do you want it so much to be Sass? Isn’t it even better if it’s pure CSS?

**Comment by HugoGiraudel** [comment]
Ping @mmjaeger. :)
