### ISSUE TITLE
Convert a hex color variable to a string?

### ISSUE THREAD

**Issue by maxx1128** [HugoGiraudel/ama#65]
Hey Hugo, I have a bizarre Sass issue I need some help with.

I'm making a fork of Pattern Lab and am trying to show the color hex values in the library. My current strategy is taking the hex value (in a variable), turning it into a string, and putting that string as a pseudo-element's content that's positioned in the library.

I've tried using the inspect() function to no luck, and frequent google searches led to no other ideas so far about turning a hex value into a string for a pseudo-element. Any ideas about how to accomplish this?

**Comment by HugoGiraudel** [comment]
Hey Max.

You are on the right track. `inspect(..)` does return a string representation of the value. However, the `content` property expects a quoted string. You only have to use the `quote(..)` function to make it work.

```scss
.foo::after {
  content: quote(inspect($color))
}
```

Best. :)

**Comment by maxx1128** [comment]
Huzzah, it worked! Glad to finally have worked this into my project, thanks!
<img width="1009" alt="featured" src="https://cloud.githubusercontent.com/assets/10790736/15630312/739c8ef6-2503-11e6-8f2f-2676b3045651.png">

**Comment by HugoGiraudel** [comment]
Lovely. :)
