### ISSUE TITLE
Your new site

### ISSUE THREAD

**Issue by ryanwsnow** [HugoGiraudel/ama#66]
I read your stuff all the time, but now I find your site unreadable. Is suppose to look like code? very hard to read with low contrast, awkward spacing, no clear headlines, and all the wrong things highlighted. It just looks like raw markdown. I am assuming something is wrong.

**Comment by HugoGiraudel** [comment]
Hey there. It is supposed to look like raw Markdown, that’s the whole point.

I am sorry you don’t appreciate this redesign. If you use a RSS/Atom reader, you can definitely just use the feed in the reader of your choice to browse the content of articles. 

If you are a user of custom stylesheets and you still want to browse this site, you could also overwrite some styles that you don’t want.

Sorry for the inconvenience.
