### ISSUE TITLE
That new nav bar is big. 

### ISSUE THREAD

**Issue by jachaf6746** [HugoGiraudel/ama#67]
Hey Hugo, 

Great work on the new site, I really like it. Could you explain the desktop navigation menu please? Particularly the size of the navigation menu. It's quite large. 

Thanks.

**Comment by HugoGiraudel** [comment]
Hey.

I was trying something with the Golden ratio. Its size is `100% - (100% / 1.618)`. :)

I figured it was not a problem the sidebar was that big given that the main content should not be much wider anyway for readability concern. So I were to reduce the width of the sidebar, the main area would indeed be bigger but the content width would stay the same.

**Comment by jachaf6746** [comment]
I feel that. 

Okay cool I was trying to figure out how you arrived at 38.1953% for the width. 

Do you think ocular dominance affects readability with that UI design? I'm no eye expert (or design expert) but I just wonder whether left eye dominant readers would find that aesthetic as pleasing as I do as a right eye dominant viewer.

Side note: thanks for responding and for being a super helpful resource with your code/blog/book/other stuff. I geek out to Sass docs on the daily.

**Comment by HugoGiraudel** [comment]
Aww you’re too kind, thank you. 😊

I’ll be honest and admit design is definitely not my strong suit, to the point where I am not sure what you mean by “ocular dominance.” I actually did not know such a thing existing, interesting. Any resource to know more about it? Or care to explain a bit?

**Comment by jachaf6746** [comment]
Honestly, I haven't heard it talked about much in design (or anywhere but my freshman psychology class), so take this theory with a grain of salt, but essentially we have these neurons in the visual cortex called ocular dominance columns that are more responsive to input from one eye than the other. So like right handedness vs. left handedness, but with eyes. I'm guessing that's one of the reasons why folks with heavy content on their page tend to center it, as it gives content equivalent semantic meaning for readers of either visual preference. 

I see why you went with the two-column layout for your site though, because it's not like you have ads or anything to fill up the right, and because the golden ratio is a glorious thing in both name and geometric fantasticalness. 

Building off our theory of ocular dominance, my only concern with using it as an overall page layout would be whether the composition presents readability concerns for viewers who are left-eye dominant and naturally drawn away from the content.

I am right eye dominant though, so as a simple reader and fan of your site, I have no quarrels with the new design:)

Still, could be an interesting test for your left eye dominant friends. Or if you know any pirates. 

If you want to find out yours just for the hell of it, this [link](http://www.diyphotography.net/a-neat-trick-to-determine-your-dominant-eye/) describes a fairly easy test.

**Comment by HugoGiraudel** [comment]
Thank you very much for the explanation. :)

**Comment by jachaf6746** [comment]
Sure thing, thanks for the help!
