### ISSUE TITLE
how do you convince clients web developer is a real job ?

### ISSUE THREAD

**Issue by nicodev3** [HugoGiraudel/ama#70]
Hi Hugo,

Firstly, sorry for my bad english, i am French as you are, but not so fluent you are :-)

Here is my question, or maybe the debate I'd like to open : how would you explain to potential clients that building a website worth hiring a web designer/developer. This question sounds weird, but i often meet people saying "you can build your own website, no need to pay, there is WordPress, Wix..". I tend to answer you can bake your own bread if you buy a prebaked one and put it in your microwave oven, but the taste and quality will be not as good as a real one. They don't understand technical arguments, and even not design or economic arguments. 

Seems like the web is infested with our modern ideology : everything is free (sure it's not !).

Would like to read your thought about that. Thanks Hugo.

**Comment by HugoGiraudel** [comment]
Hey,

The thing is I don’t work with clients much. I am not a freelancer for that very reason, and when I used to work at Edenspiekermann, I was not the one directly dealing with clients. Therefore I might not be the best person to tell you how to proceed with this. I’ll try nevertheless.

One important thing to mention is that you cannot really convince anyone to do anything, let alone to spend money on a thing they don’t believe in. To make them understand why it would be worth it, you have to tackle this on several fronts. 

Let’s name a few of the many things that come under consideration when building a website:

- Design
- Implementation quality (scalability, maintainability)
- Accessibility
- Search engine optimisation
- Performance
- Content management

Unfortunately, only a few of these topics actually matter to a client. For instance, very few people will actually care about implementation quality, which will have a direct impact on scalability, code maintenance and usually performance. Likewise with accessibility, where the typical answer is “but it’s not my target audience”. Insert sad face here.

The three big things that can probably weigh in the balance are design consistency, search engine optimisation and the ease with which they can update their content. Now, most all-inclusive solutions usually have a very decent CMS, like WordPress, so this is not something you can really improve. 

In the end, you can argue you will have a lot of amplitude to implement the customer’s design, and that you will optimise the site for search engines better than a full-blown CMS, which might have a direct impact in the client’s sales/benefits. Performance is also likely to be better, which impacts on SEO as well.

Just keep in mind that in the end, if the client doesn’t want to spend a penny, they won’t. No matter what you say.
