### ISSUE TITLE
What's your trick/talent in being able to write so many articles in short time?

### ISSUE THREAD

**Issue by alexprut** [HugoGiraudel/ama#72]
Hi Hugo,
It takes me lot of time writing a blog post or article, finding the argument, how to explain it, typo checks and so on ...
I've noticed you've been writing for a long period of time so far and have published new articles regularly within short period time (sometimes one a day), I think you also sleep + eat + work, where do you find all that time?
- How do you find the argument/title?
- How much it takes you to write an article/blog post?
- How much it takes you to fix text/code typos?
- What's your secret? :)
Thanks,

btw nice #ftf16 talk

**Comment by HugoGiraudel** [comment]
Hey there. :)

> How do you find the argument/title?

I would not worry too much about the title itself. To be fair, if you manage to write an article, you should be able to name it pretty easily. The main point should come up naturally and a title should emerge. I’d advise finishing with the title. 

> How much it takes you to write an article/blog post?

Usually between 30 minutes and one hour but I am a fast writer and a fast typer. If you are interested, I wrote up about this very process a long time ago. I believe that’s still very relevant. Here is [the article](http://hugogiraudel.com/2014/05/26/how-i-came-to-write-for-the-web/#about-actually-writing).

> How much it takes you to fix text/code typos?

I mostly write for SitePoint, which involves peer reviews and a final editor review, so typos are usually caught by someone else. That being said, I always do one or two proof reads of an article once finished with it. On top of fixing typos and mistakes, it allows me to make sure the article is understandable when read from top to bottom.

> What's your secret? :)

Enjoy what you are doing, don’t overthink things and write regularly. Soon enough, it is going to be very easy.

**Comment by alexprut** [comment]
I have read the article that you have linked, it taught me some lessons:
- focus and get good in one technology (in your case SASS)
- start writing as soon as possibile, after a while it becomes easier to write
- write articles in one-shoot
Thanks @HugoGiraudel
