### ISSUE TITLE
Recommendations for upcoming developers?

### ISSUE THREAD

**Issue by asilvadesigns** [HugoGiraudel/ama#74]
Hello Hugo,

I really appreciate your work and I think you do a great job. I wanted to ask what resources books or otherwise that you would recommend to a junior developer? Thanks for your time, God bless!

**Comment by HugoGiraudel** [comment]
Hello,

For front-end developers, there is [Front-end Rescue](https://uptodate.frontendrescue.org/), a site giving you tips and resources to stay up to date with front-end development. It recommends blogs, websites, Twitter profiles, newsletters… The whole bunch.

I think the biggest problem for a junior developer nowadays is that everything can feel a bit overwhelming. There are so many things to know, so many technologies to experiment with, so many tools to try… It’s easy to feel lost.

My recommendation is to learn what you feel like learning and not what you feel like you have to learn. I expanded about this [in another question](https://github.com/HugoGiraudel/ama/issues/68). 

Find something that drives you, that excites you, and dig as deep as you want. If you don’t like it, don’t force it. Find something else, until you find your thing. Feel free to experiment with new technologies when you’re curious about them, yet don’t feel obligated to become an expert in everything you touch.

I hope it helps. :)
