### ISSUE TITLE
Feedback on a front-end survey I will be running?

### ISSUE THREAD

**Issue by ashleynolan** [HugoGiraudel/ama#75]
Hi Hugo,

I’m going to be releasing a front-end tooling survey to the community next week – something I [also did last year](https://ashleynolan.co.uk/blog/frontend-tooling-survey-2015-results).

I wanted to make sure it is representative of the industry today and so if you had chance, I would massively appreciate any feedback on the questions and answers I’ve chosen prior to me releasing it.

The survey is currently available at this link > http://ashn.uk/survey-tooling-2016

Obviously, if you could not release the link to anyone else for the moment, as if I change any of the questions or answers in the next couple of days this would mean any results collected would get skewed.

Thanks!
Ash

**Comment by HugoGiraudel** [comment]
Hello. :)

I find the notion of “approaches” very vague.

SMACSS, Object Oriented CSS (OOCSS), Atomic Design, ITCSS, Suit CSS and BEM are methodologies.
CSS Modules is a methodology coupled with tooling.
Autoprefixer, Susy and Modernizr are tools.

Other than that, I find it interesting. :)

**Comment by ashleynolan** [comment]
Thanks for taking a look – appreciate it.

Do you think changing the title of this question to the below would make it any clearer?

"Please indicate your experience with the following CSS methodologies and tools:"

Or do you think I should split out the definite tools (Autoprefixer, Susy, Modernizr) into a separate question to the methodologies for clarity?

**Comment by HugoGiraudel** [comment]
I would split. I think talking about methodologies and tools separately makes more sense. You could even add more tools to that list then. :)

**Comment by ashleynolan** [comment]
Ok, I’ll do that then.  Are there any other tools in particular that you’d be interested in finding out information about?

**Comment by HugoGiraudel** [comment]
Not sure. They are so many of them. :D

**Comment by ashleynolan** [comment]
Ok 😄  I added Stylelint as I thought it would be interesting to find out usage of that as well.

I’ve now [pushed the survey live](https://ashleynolan.co.uk/blog/frontend-tooling-survey-2016) and made sure to thank you for your feedback in my post.

Thanks!

**Comment by HugoGiraudel** [comment]
Cheers! :)
