### ISSUE TITLE
Fintech & Accessibility

### ISSUE THREAD

**Issue by CesarFerratBourdon** [HugoGiraudel/ama#80]
Bonjour Hugo,

While living in San Francisco I became friend with Kaelig and he strongly advised me to reach out to you :)

Coming from a business background (MBA), I switched to web development 2 years ago and just got hired in Oslo by an insurance/bank as a front-end dev.

As I never worked in this industry before and still being a Junior I was wondering if you had some resources/blogs/books to recommend regarding the FinTech industry and also Accessibility to get me up to speed.

Thanks a lot for your help and congrats on your excellent blog.

Cesar

**Comment by HugoGiraudel** [comment]
Hey Cesar,

Awwww @Kaelig is awesome. You’re lucky to have him around! Say hi next time you meet him. :)

So regarding FinTech, I’m not sure I can tell you much. I personally quite dislike that term as I find it rather irrelevant, but maybe I just lack of business background. ¯\\\_(ツ)\_/¯

Now when it comes to banking, the funny thing is that I worked in Crédit Agricole –a big ass bank– in France for a few years, and now am running at N26 in Germany, which is deeply anchored in the startup culture.

Obviously, both are very different. And both have good sides and bad sides, but I would need more than a few lines to describe my feelings about all this. One thing they have in common however  is that *legal* is omnipresent. In France, we used to call that “conformity” (or “compliance”); here we simply talk about “legal”. This is basically everything that goes against us doing crazy shit: data privacy, terms and conditions, security, banking rules… It’s not all bad of course and it’s actually super important to have this but sometimes, it ends up being quite annoying.

Now, accessibility. First off, thanks for taking this in consideration, that’s great. This is basically all I’m doing at N26. Pushing for it, fighting for it, trying to make our design more inclusive and our platform more accessible. It’s hard. It’s very hard. You’ll find out that convincing POs and business persons that this is the right thing to do is usually not enough. If money or reputation doesn’t come in the discussion, this is basically ruled out as a secondary feature, or some kind of sprinkle on top of the cake if we ever have time (hint: we never do).

An advice I can give you is: do it anyway. It pays off. Do the work correctly from the ground up to make everything as accessible as you can. It doesn’t take much longer and it makes a huge difference. Accessibility on the web isn’t about doing more work; it’s about doing the correct work. Try to educate people around you about the values of working with accessibility in mind; designers, POs, other developers… Eventually, everybody can contribute to it. Or at least not actively work against it. It takes time and energy, but as far as I’m concerned, that’s all my work is about, right now. At the end of the day, this is how you make a difference, if only for some users. Code doesn’t matter that much.

You wanted resources I believe, so I can recommend the Accessibility Styleguide from Carie Fisher: http://a11y-style-guide.com/style-guide/. It’s a great resource to get started. The Accessibility Guidelines from Vox Media are also fantastic and give good hints about how to involve everyone in accessibility work: http://accessibility.voxmedia.com/.

**Comment by CesarFerratBourdon** [comment]
Thanks a lot for all these details! I really appreciate :)
