### ISSUE TITLE
Checkbox styling 

### ISSUE THREAD

**Issue by OluwoleDove** [HugoGiraudel/ama#81]
Hi I came across your styling for check boxes on this site. https://tympanus.net/codrops/2012/09/13/button-switches-with-checkboxes-and-css3-fanciness/.

The one that was styled to toggle between on and off states is really cool. I tried and it worked just fine, I like to make use of it in a simple app. Thanks.

**Comment by HugoGiraudel** [comment]
Hey. Funny thing, this is one of the first articles I’ve written on web development. It’s getting very old. :)

Thanks for the kind words anyway!

**Comment by OluwoleDove** [comment]
Yeah it's really cool and brilliant, I'll like to adapt one of the CSS
styles.
