### ISSUE TITLE
Feedback needed on Kuoll

### ISSUE THREAD

**Issue by stepnov** [HugoGiraudel/ama#84]
Hi Hugo,

I am one of the founders of a technology start-up [Kuoll.com](url). I am reaching out to the top Web Development experts to see if our new product, which allows getting debug-charged error reports with each new release, could be helpful.

It would be really nice if you can try Kuoll out and give us a feedback.

Thanks,

P.S. See you in Minsk, I am originally from Belarus, Minsk

**Comment by HugoGiraudel** [comment]
Hello Eugene!

I had a look at Kuoll the other day and it looks very nice. We use TrackJS at work, but Kuoll seems to take error reporting one step further. Congratulations on this well thought and designed product.

I didn’t try it and I don’t think I’ll be able to given we can’t just change our error reporting for just a couple of weeks for the sake of trying. But it seems pretty cool nevertheless! :)

Best,

**Comment by stepnov** [comment]
Hugo, thanks for the reply.

Just wanted to clarify one thing. Why is it difficult to change error 
reporting product?
Maybe we in Kuoll need something to add to make switching between two 
products easier?

Thanks again,

Eugene Stepnov
*Kuoll, Inc.*
eugene@kuoll.com

**Comment by HugoGiraudel** [comment]
Because as a bank, we cannot just change services without going through a security and data privacy audit, and that’s a process too costly for just a trial. :)

**Comment by stepnov** [comment]
Thank you,

Do you know someone who will be interested in trying Kuoll and it will be 
not so difficult for them? :)

Best,

Eugene Stepnov
*Kuoll, Inc.*
eugene@kuoll.com
