### ISSUE TITLE
How can I remove margin-bottom from last row of my Mixin?

### ISSUE THREAD

**Issue by touhid-rahman** [HugoGiraudel/ama#91]
[https://codepen.io/touhid_rahman/pen/YYpxqx](https://codepen.io/touhid_rahman/pen/YYpxqx)

I have developed a fluid column grid using SASS. For example, +columns(6) divides all elements in 6 equal width columns.

The problem is, I don't want margin-bottom for last row of elements. How can I remove this margin-bottom?

**Comment by HugoGiraudel** [comment]
Hello.

You can use [this technique](https://keithclark.co.uk/articles/targeting-first-and-last-rows-in-css-grid-layouts/) to target the last row of a grid layout. It outputs quite a verbose selector but it does what you want.

```diff
+.column:nth-child(#{$column_number}n+1):nth-last-child(-n+#{$column_number}),
+.column:nth-child(#{$column_number}n+1):nth-last-child(-n+#{$column_number}) ~ .column 
+  margin-bottom: 0
```
