### ISSUE TITLE
Removing Un-used CSS, Images & JS codes in Sublime Text 3

### ISSUE THREAD

**Issue by touhid-rahman** [HugoGiraudel/ama#93]
How can I remove un-used CSS, Images & JS codes from my project?

If a project is bigger; usually there are lots of trash codes specifically if the project is built based on another similar project.

So, how can I remove all the un-necessary CSS, Images & JS codes; with or without help of any package?

Thanks!

**Comment by HugoGiraudel** [comment]
As mentioned in #90, Sublime Text is not an IDE, it’s only a text editor. It means there is no way a package can tell you what is used in your project and what is not. Only an IDE could potentially do that.

Even in an IDE, I’m not sure there is a silver-bullet for such a problem. I personally tend to check for usage through searching (sometimes regex based) within a project source code. It has its limits of course.

For CSS, you could have a look at [uncss](https://github.com/giakki/uncss) which does the job pretty well. It takes a bit of time to set it up correctly though.
