### ISSUE TITLE
How can I define multiple SASS/SCSS variables at a time?

### ISSUE THREAD

**Issue by touhid-rahman** [HugoGiraudel/ama#94]
In-stead of defining multiple variables separately like:
```
$logo_text_color: $white
$menu_link_color: $white
$menu_icon_color: $white
```

Is there any way to define them together at a time; something like this?
`$logo_text_color: $menu_icon_color: $menu_link_color: $white`

**Comment by HugoGiraudel** [comment]
There is no way to do this. And there is no good reason to do this either. Simply define your variables one by one. :)
